version: '3.8'

services:
  ai-trading-bot:
    build: .
    container_name: ai-trading-signals-bot
    ports:
      - "8080:8080"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN:-}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID:-}
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - trading-bot-network

networks:
  trading-bot-network:
    driver: bridge

volumes:
  logs:
    driver: local

